name: marken_iot
description: "A new Flutter project."
publish_to: 'none'

version: 1.25.0+20

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_secure_storage: ^10.0.0
  google_sign_in: ^6.2.1
  mobile_scanner: ^7.1.4
  shared_preferences: ^2.3.2
  flutter_svg: ^2.0.10
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  image_picker: ^1.0.7
  google_mlkit_barcode_scanning: ^0.14.2
  url_launcher: ^6.3.2
  flutter_local_notifications: ^20.0.0
  connectivity_plus: ^7.0.0
  crypto: ^3.0.6
  fluttertoast: ^8.2.4
  workmanager: ^0.6.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # âœ… ONLY for App Icon
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/images/diagnose.png

# âœ… App Icon Config (ONLY ICON)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon.png
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

